### PR TITLE
guides folder added

### PR DESCRIPTION
**Pull request by admasodaniel**
added 'guides' directory in order to support the new wix-docs file structure requirement and display the main guides.

### CODE REVIEW

**Comment by agankarin** [comment]
@admasodaniel This repo is a core repo representing Corvid API and used by 3 different systems, including [corvid-types](https://github.com/wix-incubator/corvid-types)
This repo generated and maintenance by [docworks](https://www.npmjs.com/package/docworks-cli), this tool also uses this repo to generate different models, like `d.ts` file
This PR doesn't describe Corvid API, it's more an article 
Also it's changing the file structure and might affect other customers 
This change seems to be relevant only for the new API website(system #4), and should be implemented there.

**Comment by alon-cohen** [comment]
Hey @agankarin,
this change has been verified with @roibWix. I understand your feedback, but not the solution?
this change is an infrastructure for the new Wix Docs, extending the functionality we had in the old viewer, and allowing us to add markdown articles to share with users.

**Comment by galElmalah** [comment]
@agankarin I understand your concerns.
is it possible that during your process you will update another repo, lets say wix-docs-corvid-blabla?
so we will have two repos that  are always in sync and we will add the guides to the other instance?

**Comment by agankarin** [comment]
@alon-cohen @galElmalah To me it sounds that the new viewer should be able to read its data from different sources: 
1. The corvid API json model(this repo) 
2. Corvid articles 
The app will merge those sources and display them(this is what happening today)
I don't see any reason why to duplicate this data, we should have only one true source

**Pull request closed without merging**
